# tofu/providers.tf
# Configures all providers with connection details.
# Credentials come from sops-encrypted secrets — never hardcoded.

# ── SOPS provider ─────────────────────────────────────────────────
# The SOPS provider needs no configuration block.
# It automatically finds your age key at:
# ~/.config/sops/age/keys.txt
# No extra setup needed beyond having the key in place.

# ── Read encrypted secrets ────────────────────────────────────────
data "sops_file" "secrets" {
  source_file = "secrets.sops.yaml"
  # Reads and decrypts secrets.sops.yaml at plan/apply time.
  # Decrypted values live only in memory — never written to disk.
  # The encrypted file is listed in .gitignore — never committed.
}

# ── Proxmox provider ──────────────────────────────────────────────
provider "proxmox" {
  endpoint = var.proxmox_endpoint
  # The Proxmox API URL — defined in terraform.tfvars.
  # Format: https://\<ip\>:8006/
  # Trailing slash is required by the bpg/proxmox provider.

  api_token = data.sops_file.secrets.data["proxmox_api_token"]
  # Reads the decrypted API token from secrets.sops.yaml.
  # Format: opentofu@pve!tofu=<uuid>:<secret>
  # Generated by the Ansible api_tokens.yml task.

  insecure = true
  # Disables TLS certificate verification.
  # Proxmox ships with a self-signed certificate by default.
  # Set to false once you have a valid certificate in place.

  ssh {
    agent    = true
    # Uses the running ssh-agent for SSH operations.
    # Run: eval $(ssh-agent) && ssh-add ~/.ssh/cs3admin@cs3.lab
    # before running any tofu commands.

    username = "root"
    # Root is required for Proxmox node SSH access.
    # The bpg/proxmox provider uses SSH for operations the
    # API does not expose directly, such as uploading ISOs.
  }
}
